///|
pub extend LiquidValue with ToJson::{to_json}

///|
pub extend ErrorPolicy with ToJson::{to_json}

///|
pub extend LiquidContext with ToJson::{to_json}

///|
pub extend Filter with ToJson::{to_json}

///|
pub extend ForLoopModifiers with ToJson::{to_json}

///|
pub extend LiquidNode with ToJson::{to_json}

///|
pub extend WhitespaceControl with ToJson::{to_json}

///|
pub extend TemplateWithLayout with ToJson::{to_json}

///|
pub extend LiquidTemplate with ToJson::{to_json}
