#!/usr/bin/env ruby
# Generate a bounded compatibility corpus from Shopify's pinned Ruby implementation.
# Install outside the project: gem install liquid -v 5.4.0 --no-document
# Regenerate: ruby tools/reference_cases.rb --write
# Verify:    ruby tools/reference_cases.rb --check
gem "liquid", "= 5.4.0"
require "liquid"
require "json"
require "open3"

abort "Usage: #{$PROGRAM_NAME} --write|--check" unless ARGV.length == 1 && %w[--write --check].include?(ARGV[0])

cases = {
  "literal and typed equality" => "{% if 6 == '6' %}bad{% else %}typed{% endif %}",
  "right associative conditions" => "{% if true or false and false %}yes{% else %}no{% endif %}",
  "quoted filter delimiters" => "{{ 'a,b:c|d' | replace: 'a,b:c|d', 'ok' }}",
  "loop modifiers" => "{% assign items = 'a,b,c,d,e,f,g,h' | split: ',' %}{% for x in items reversed offset:6 limit:2 %}{{ x }}{% endfor %}",
  "empty loop fallback" => "{% assign items = '' | split: ',' %}{% for x in items %}bad{% else %}empty{% endfor %}",
  "typed case branches" => "{% case 6 %}{% when '6' %}bad{% when 6 %}number{% endcase %}",
  "case variable choice" => "{% assign expected = 'admin' %}{% case 'admin' %}{% when expected %}yes{% endcase %}",
  "cycle state" => "{% assign xs = 'a,b,c' | split: ',' %}{% for x in xs %}{% cycle 'odd', 'even' %},{% endfor %}",
  "ifchanged state" => "{% assign xs = 'a,a,b,a' | split: ',' %}{% for x in xs %}{% ifchanged %}{{ x }}{% endifchanged %}{% endfor %}",
  "counter isolation" => "{% assign x = 10 %}{% increment x %}|{% increment x %}|{% decrement x %}|{{ x }}",
  "array concatenation" => "{% assign a = 'a,b' | split: ',' %}{% assign b = 'c,d' | split: ',' %}{{ a | concat: b | join: '-' }}",
  "assigned float divisor" => "{% assign d = 4.0 %}{{ 10 | divided_by: d }}",
  "float filter chain" => "{% assign d = 2.0 | times: 2 %}{{ 10 | divided_by: d }}",
  "negative integer division" => "{{ -10 | divided_by: 4 }}",
  "unicode slicing" => "{{ 'a😀中bc' | slice: 1, 2 }}",
  "negative slice" => "{{ 'abcdefghij' | slice: -3, 2 }}",
  "truncate suffix budget" => "{{ 'abcdefghij' | truncate: 4 }}|{{ 'abcdefghij' | truncate: 6, '--' }}",
  "default false option" => "{{ false | default: 'fallback', allow_false: true }}",
  "nested control flow" => "{% assign xs = 'a,b,c' | split: ',' %}{% for x in xs %}{% if x == 'b' %}{% continue %}{% endif %}{{ x }}{% endfor %}",
  "whitespace control" => "a \n {{- 'b' -}} \n c",
}

source = "// Generated by tools/reference_cases.rb with Shopify Liquid 5.4.0.\n"
cases.each do |name, template|
  expected = Liquid::Template.parse(template, error_mode: :strict).render!({}, strict_filters: true)
  source << <<~MBT

    ///|
    test #{JSON.generate("reference: " + name)} {
      let context = LiquidContext::new()
      let source = #{JSON.generate(template)}
      let expected = #{JSON.generate(expected)}
      assert_eq(@liquid.compile(source).unwrap().render(context).unwrap(), expected)
      assert_eq(parse(source).render(LiquidContext::new()), expected)
    }
  MBT
end
formatted, errors, status = Open3.capture3("moonfmt", "-", stdin_data: source)
abort errors unless status.success?
destination = File.expand_path("../reference_compatibility_test.mbt", __dir__)
if ARGV[0] == "--write"
  File.write(destination, formatted)
elsif !File.exist?(destination) || File.read(destination) != formatted
  abort "Reference corpus differs. Regenerate with --write and review the diff."
end
puts "Verified #{cases.length} reference cases against Liquid #{Liquid::VERSION}."
